apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-generic
  namespace: go-generic
  labels:
    app: go-generic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-generic
  template:
    metadata:
      labels:
        app: go-generic
    spec:
      containers:
      - name: go-generic
        image: go-generic
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      restartPolicy: Always
