apiVersion: v1
kind: Service
metadata:
  name: go-generic
  namespace: go-generic
  labels:
    app: go-generic
spec:
  type: ClusterIP
  selector:
    app: go-generic
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
